-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- SCHEMA FOURPARKSDATABASE
-- -----------------------------------------------------
DROP DATABASE `FOURPARKSDATABASE`;
CREATE SCHEMA IF NOT EXISTS `FOURPARKSDATABASE` DEFAULT CHARACTER SET UTF8MB3 ;
USE `FOURPARKSDATABASE` ;

-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`DOCUMENTTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`DOCUMENTTYPE` (
  `IDDOCTYPE` VARCHAR(3) NOT NULL,
  `DESCDOCTYPE` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IDDOCTYPE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`USER` (
  `IDUSER` VARCHAR(13) NOT NULL,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PHONE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IDUSER`, `IDDOCTYPEFK`),
  INDEX `FK_USER_DOCUMENTTYPE_IDX` (`IDDOCTYPEFK` ASC) VISIBLE,
  CONSTRAINT `FK_USER_DOCUMENTTYPE`
    FOREIGN KEY (`IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`DOCUMENTTYPE` (`IDDOCTYPE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;

-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`USER_AUTHENTICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`USER_AUTHENTICATION` (
  `IDUSER` VARCHAR(13) NOT NULL,
  `IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL,
  `PASSWORD` VARCHAR(200) NOT NULL,
  `ROLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDUSER`, `IDDOCTYPEFK`),
  UNIQUE KEY `UNIQUE_USERNAME` (`USERNAME`), -- Restricción de unicidad en USERNAME
  CONSTRAINT `FK_USER_AUTHENTICATION_USER`
    FOREIGN KEY (`IDUSER` , `IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`USER` (`IDUSER` , `IDDOCTYPEFK`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;

-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`ADDRESS` (
  `COORDINATESX` FLOAT(10,4) NOT NULL,
  `COORDINATESY` FLOAT(10,4) NOT NULL,
  `DESCADDRESS` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`COORDINATESX`, `COORDINATESY`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;



-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`CLIENT` (
  `USER_IDUSER` VARCHAR(13) NOT NULL,
  `USER_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  `SCORE` INT NOT NULL,
  PRIMARY KEY (`USER_IDUSER`, `USER_IDDOCTYPEFK`),
  CONSTRAINT `FK_CLIENTE_USER1`
    FOREIGN KEY (`USER_IDUSER` , `USER_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`USER` (`IDUSER` , `IDDOCTYPEFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`CARD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`CARD` (
  `IDCARD` INT NOT NULL AUTO_INCREMENT,
  `SERIALCARD` VARCHAR(16) NOT NULL,
  `EXPIRYDATECARD` DATE NOT NULL,
  `CVVCARD` VARCHAR(3) NOT NULL,
  `IDPERSONDETAILSFK` INT NOT NULL,
  `CLIENTE_USER_IDUSER` VARCHAR(13) NOT NULL,
  `CLIENTE_USER_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IDCARD`),
  INDEX `FK_CARD_CLIENTE1_IDX` (`CLIENTE_USER_IDUSER` ASC, `CLIENTE_USER_IDDOCTYPEFK` ASC) VISIBLE,
  CONSTRAINT `FK_CARD_CLIENTE1`
    FOREIGN KEY (`CLIENTE_USER_IDUSER` , `CLIENTE_USER_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`CLIENT` (`USER_IDUSER` , `USER_IDDOCTYPEFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`CITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`CITY` (
  `IDCITY` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `B_TOP` DECIMAL(10, 4) NOT NULL,
  `B_BOTTOM` DECIMAL(10, 4) NOT NULL,
  `B_LEFT` DECIMAL(10, 4) NOT NULL,
  `B_RIGHT` DECIMAL(10, 4) NOT NULL,
  PRIMARY KEY (`IDCITY`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`CUSTOMERACTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`CUSTOMERACTION` (
  `IDACTION` INT NOT NULL AUTO_INCREMENT,
  `DESCACTION` VARCHAR(45) NOT NULL,
  `PERSON_IDPERSON` VARCHAR(13) NOT NULL,
  `PERSON_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IDACTION`),
  INDEX `FK_ACTION_PERSON_IDX` (`PERSON_IDPERSON` ASC, `PERSON_IDDOCTYPEFK` ASC) VISIBLE,
  CONSTRAINT `FK_ACTION_PERSON`
    FOREIGN KEY (`PERSON_IDPERSON` , `PERSON_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`USER` (`IDUSER` , `IDDOCTYPEFK`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`PAYMENTMETHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`PAYMENTMETHOD` (
  `IDPAYMENTMETHOD` INT NOT NULL,
  `DESCPAYMENTMETHOD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDPAYMENTMETHOD`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`SCHEDULE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`SCHEDULE` (
  `IDSCHEDULE` INT NOT NULL,
  `STARTTIME` TIME NULL DEFAULT NULL,
  `ENDTIME` TIME NULL DEFAULT NULL,
  `SCHEDULETYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDSCHEDULE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`ADMINISTRATOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`ADMINISTRATOR` (
  `USER_IDUSER` VARCHAR(13) NOT NULL,
  `USER_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`USER_IDUSER`, `USER_IDDOCTYPEFK`),
  CONSTRAINT `FK_ADMINISTRADOR_USER1`
    FOREIGN KEY (`USER_IDUSER` , `USER_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`USER` (`IDUSER` , `IDDOCTYPEFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`PARKINGTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`PARKINGTYPE` (
  `IDPARKINGTYPE` INT NOT NULL,
  `DESCPARKINGTYPE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDPARKINGTYPE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`PARKING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`PARKING` (
  `IDPARKING` INT NOT NULL AUTO_INCREMENT,
  `NAMEPARK` VARCHAR(45) NOT NULL,
  `CAPACITY` INT NOT NULL,
  `ADDRESS_COORDINATESX` FLOAT(10,4) NOT NULL,
  `ADDRESS_COORDINATESY` FLOAT(10,4) NOT NULL,
  `PHONE` VARCHAR(10) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `CITY_IDCITY` INT NOT NULL,
  `SCHEDULE_IDSCHEDULE` INT NOT NULL,
  `ADMINISTRADOR_USER_IDUSER` VARCHAR(13) NOT NULL,
  `ADMINISTRADOR_USER_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  `PARKINGTYPE_IDPARKINGTYPE` INT NOT NULL,
  PRIMARY KEY (`IDPARKING`),
  INDEX `FK_PARKING_CITY_IDX` (`CITY_IDCITY` ASC) VISIBLE,
  INDEX `FK_PARKING_SCHEDULE_IDX` (`SCHEDULE_IDSCHEDULE` ASC) VISIBLE,
  INDEX `FK_PARKING_ADDRESS` (`ADDRESS_COORDINATESX` ASC, `ADDRESS_COORDINATESY` ASC) VISIBLE,
  INDEX `FK_PARKING_ADMINISTRADOR1_IDX` (`ADMINISTRADOR_USER_IDUSER` ASC, `ADMINISTRADOR_USER_IDDOCTYPEFK` ASC) VISIBLE,
  INDEX `FK_PARKING_PARKINGTYPE1_IDX` (`PARKINGTYPE_IDPARKINGTYPE` ASC) VISIBLE,
  CONSTRAINT `FK_PARKING_ADDRESS`
    FOREIGN KEY (`ADDRESS_COORDINATESX` , `ADDRESS_COORDINATESY`)
    REFERENCES `FOURPARKSDATABASE`.`ADDRESS` (`COORDINATESX` , `COORDINATESY`),
  CONSTRAINT `FK_PARKING_CITY`
    FOREIGN KEY (`CITY_IDCITY`)
    REFERENCES `FOURPARKSDATABASE`.`CITY` (`IDCITY`),
  CONSTRAINT `FK_PARKING_SCHEDULE`
    FOREIGN KEY (`SCHEDULE_IDSCHEDULE`)
    REFERENCES `FOURPARKSDATABASE`.`SCHEDULE` (`IDSCHEDULE`),
  CONSTRAINT `FK_PARKING_ADMINISTRADOR1`
    FOREIGN KEY (`ADMINISTRADOR_USER_IDUSER` , `ADMINISTRADOR_USER_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`ADMINISTRATOR` (`USER_IDUSER` , `USER_IDDOCTYPEFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PARKING_PARKINGTYPE1`
    FOREIGN KEY (`PARKINGTYPE_IDPARKINGTYPE`)
    REFERENCES `FOURPARKSDATABASE`.`PARKINGTYPE` (`IDPARKINGTYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`RESERVATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`RESERVATION` (
  `IDRESERVATION` INT NOT NULL,
  `STARTTIMERES` TIME NOT NULL,
  `ENDTIMERES` TIME NOT NULL,
  `PARKING_IDPARKING` INT NOT NULL,
  `VEHICLE_IDVEHICLE` VARCHAR(6) NOT NULL,
  `VEHICLE_VEHICLETYPE_IDVEHICLETYPE` INT NOT NULL,
  `CREATIONDATERES` DATE NOT NULL,
  `TOTALRES` INT NULL DEFAULT NULL,
  `CLIENTE_USER_IDUSER` VARCHAR(13) NOT NULL,
  `CLIENTE_USER_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  `LICENSEPLATE` VARCHAR(6) NOT NULL,
  `RESERVATIONCOL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDRESERVATION`),
  INDEX `FK_RESERVATION_PARKING_IDX` (`PARKING_IDPARKING` ASC) VISIBLE,
  INDEX `FK_RESERVATION_CLIENTE1_IDX` (`CLIENTE_USER_IDUSER` ASC, `CLIENTE_USER_IDDOCTYPEFK` ASC) VISIBLE,
  CONSTRAINT `FK_RESERVATION_PARKING`
    FOREIGN KEY (`PARKING_IDPARKING`)
    REFERENCES `FOURPARKSDATABASE`.`PARKING` (`IDPARKING`),
  CONSTRAINT `FK_RESERVATION_CLIENTE1`
    FOREIGN KEY (`CLIENTE_USER_IDUSER` , `CLIENTE_USER_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`CLIENT` (`USER_IDUSER` , `USER_IDDOCTYPEFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`INVOICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`INVOICE` (
  `IDINVOICE` INT NOT NULL,
  `TOTALINVOICE` INT NOT NULL,
  `DATEINVOICE` DATE NOT NULL,
  `PAYMENTMETHOD_IDPAYMENTMETHOD` INT NOT NULL,
  `SUBTOTALINVOICE` INT NULL DEFAULT NULL,
  `IDRESERVATION` INT NOT NULL,
  PRIMARY KEY (`IDINVOICE`),
  INDEX `FK_INVOICE_PAYMENTMETHOD_IDX` (`PAYMENTMETHOD_IDPAYMENTMETHOD` ASC) VISIBLE,
  INDEX `FK_INVOICE_RESERVATION1_IDX` (`IDRESERVATION` ASC) VISIBLE,
  CONSTRAINT `FK_INVOICE_PAYMENTMETHOD`
    FOREIGN KEY (`PAYMENTMETHOD_IDPAYMENTMETHOD`)
    REFERENCES `FOURPARKSDATABASE`.`PAYMENTMETHOD` (`IDPAYMENTMETHOD`),
  CONSTRAINT `FK_INVOICE_RESERVATION1`
    FOREIGN KEY (`IDRESERVATION`)
    REFERENCES `FOURPARKSDATABASE`.`RESERVATION` (`IDRESERVATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`RATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`RATE` (
  `IDRATE` INT NOT NULL,
  `COSTRATE` INT NOT NULL,
  PRIMARY KEY (`IDRATE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`SCORESYSTEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`SCORESYSTEM` (
  `IDPOINTS` INT NOT NULL,
  `PARKING_IDPARKING` INT NOT NULL,
  `RESERVATIONSCORE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IDPOINTS`),
  INDEX `FK_SCORESYSTEM_PARKING_IDX` (`PARKING_IDPARKING` ASC) VISIBLE,
  CONSTRAINT `FK_SCORESYSTEM_PARKING`
    FOREIGN KEY (`PARKING_IDPARKING`)
    REFERENCES `FOURPARKSDATABASE`.`PARKING` (`IDPARKING`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;




-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`USERDETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`USERDETAILS` (
  `IDUSERDETAILS` INT NOT NULL,
  `USER` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ATTEMPTS` INT NOT NULL,
  `BLOCK` TINYINT NOT NULL,
  `CLIENT_IDUSER` VARCHAR(13) NOT NULL,
  `CLIENT_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IDUSERDETAILS`),
  INDEX `FK_USERDETAILS_CLIENT_IDX` (`CLIENT_IDUSER` ASC, `CLIENT_IDDOCTYPEFK` ASC) VISIBLE,
  CONSTRAINT `FK_USERDETAILS_CLIENT`
    FOREIGN KEY (`CLIENT_IDUSER` , `CLIENT_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`USER` (`IDUSER` , `IDDOCTYPEFK`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`VEHICLETYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`VEHICLETYPE` (
  `IDVEHICLETYPE` INT NOT NULL AUTO_INCREMENT,
  `DESCVEHICLETYPE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDVEHICLETYPE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`PARKINGSPACE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`PARKINGSPACE` (
  `IDPARKINGSPACE` INT NOT NULL,
  `TOTALVEHICLEDISP` INT NOT NULL,
  `AVAILABLEVEHICLEDISP` VARCHAR(45) NOT NULL,
  `PARKING_IDPARKING` INT NOT NULL,
  `RATE_IDRATE` INT NOT NULL,
  `VEHICLETYPE_IDVEHICLETYPE1` INT NOT NULL,
  `PARKING_IDPARKING2` INT NOT NULL,
  PRIMARY KEY (`IDPARKINGSPACE`, `VEHICLETYPE_IDVEHICLETYPE1`),
  INDEX `FK_PARKINGSPACE_RATE1_IDX` (`RATE_IDRATE` ASC) VISIBLE,
  INDEX `FK_PARKINGSPACE_VEHICLETYPE1_IDX` (`VEHICLETYPE_IDVEHICLETYPE1` ASC) VISIBLE,
  INDEX `FK_PARKINGSPACE_PARKING1_IDX` (`PARKING_IDPARKING2` ASC) VISIBLE,
  CONSTRAINT `FK_PARKINGSPACE_RATE1`
    FOREIGN KEY (`RATE_IDRATE`)
    REFERENCES `FOURPARKSDATABASE`.`RATE` (`IDRATE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PARKINGSPACE_VEHICLETYPE1`
    FOREIGN KEY (`VEHICLETYPE_IDVEHICLETYPE1`)
    REFERENCES `FOURPARKSDATABASE`.`VEHICLETYPE` (`IDVEHICLETYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PARKINGSPACE_PARKING1`
    FOREIGN KEY (`PARKING_IDPARKING2`)
    REFERENCES `FOURPARKSDATABASE`.`PARKING` (`IDPARKING`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB3;


-- -----------------------------------------------------
-- TABLE `FOURPARKSDATABASE`.`MANAGER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOURPARKSDATABASE`.`MANAGER` (
  `USER_IDUSER` VARCHAR(13) NOT NULL,
  `USER_IDDOCTYPEFK` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`USER_IDUSER`, `USER_IDDOCTYPEFK`),
  CONSTRAINT `FK_GERENTE_USER1`
    FOREIGN KEY (`USER_IDUSER` , `USER_IDDOCTYPEFK`)
    REFERENCES `FOURPARKSDATABASE`.`USER` (`IDUSER` , `IDDOCTYPEFK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



